kind: Service
apiVersion: v1
metadata:
  name: blog-service
  labels:
    app: blog-service
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: blog
  type: LoadBalancer
